name: Format Code

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    branches: [ main ]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: actions/setup-java@v2
        with:
          java-version: 17
      - uses: axel-op/googlejavaformat-action@v3
